#:schema node_modules/wrangler/config-schema.json
name = "handshakes-ai"
main = "src/index.js"
compatibility_date = "2024-04-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "hanshakes-db"
database_id = "5d4df5c5-66c5-4825-a212-190e7a05e02f"

[ai]
binding = "AI"
